name = "mongo-realm-worker"
type = "javascript"

account_id = "4b1e2af3a5b940ce6268c14a2d42a8bd"
workers_dev = true # or zone_id = "<ZONE ID>" if you have one
node_compat = true
compatibility_date = "2022-04-05"

[build]
command = "npm run build"

[build.upload]
dir = "build"
main = "./index.mjs"
format = "modules"

[vars]
REALM_APPID = "application-0-izzbc"
